// Todos_React/src/components/layout/Header.jsx
import React from "react";
import { Link } from "react-router-dom";

function Header() {
	return (
		<div>
			<header style={headerStyle}>
				<h1>React Todo List</h1>
				<Link style={linkStyle} to="/">
					Home
				</Link>{" "}
				|{" "}
				<Link style={linkStyle} to="/about">
					About
				</Link>
			</header>
		</div>
	);
}

const headerStyle = {
	background: "#333",
	color: "#fff",
	textAlign: "center",
	padding: "10px",
};

const linkStyle = {
	color: "#fff",
	textDecoration: "none",
};

export default Header;

// Todos_Vue/src/components/layout/Header.vue
<template>
	<header class="header">
		<h1>Vue Todo List</h1>
		<div id="nav">
			<router-link to="/">Home</router-link>|
			<router-link to="/about">About</router-link>
		</div>
	</header>
</template>

<script>
export default {
	name: "Header",
};
</script>

<style scoped>
.header {
	background: #333;
	color: #fff;
	text-align: center;
	padding: 10px;
}

.header a {
	color: #fff;
	padding-right: 5px;
	text-decoration: none;
}
</style>
