// Todos_Vue/src/components/todo/Todos.vue
<template>
	<div>
		<div v-bind:key="forEachTodo.id" v-for="forEachTodo in todos">
			<TodoItem
				v-on:del-todo="$emit('del-todo', forEachTodo.id)"
				v-bind:forEachTodo="forEachTodo"
			/>
		</div>
	</div>
</template>

<script>
import TodoItem from "./TodoItem";

export default {
	components: {
		TodoItem,
	},
	name: "Todos",
	props: ["todos"],
};
</script>

<style scoped></style>

// Todos_React/src/components/todo/Todos.jsx
import React, { Component } from "react";
import TodoItem from "./TodoItem";
import PropTypes from "prop-types";

class Todos extends Component {
	render() {
		return this.props.todos.map((forEachTodo) => (
			<TodoItem
				key={forEachTodo.id}
				todo={forEachTodo}
				handleCompletedChange={this.props.handleCompletedChange}
				handleDelete={this.props.handleDelete}
			/>
		));
	}
}

Todos.propTypes = {
	todos: PropTypes.array.isRequired,
	handleCompletedChange: PropTypes.func.isRequired,
	handleDelete: PropTypes.func.isRequired,
};

export default Todos;
