// Todos_Vue/src/components/form/AddTodo.vue
<template>
	<div>
		<form v-on:submit.prevent="onSubmit">
			<input
				type="text"
				v-model="title"
				name="title"
				placeholder="Add Todo..."
			/>
			<input type="submit" value="Submit" class="btn" />
		</form>
	</div>
</template>

<script>
export default {
	name: "AddTodo",
	data() {
		return {
			title: "",
		};
	},
	methods: {
		onSubmit() {
			const newTodo = {
				title: this.title,
				completed: false,
			};
			this.$emit("add-todo", newTodo);

			this.title = "";
		},
	},
};
</script>

<style scoped>
form {
	display: flex;
}

input[type="text"] {
	flex: 10;
	padding: 5px;
}

input[type="submit"] {
	flex: 1;
}
</style>

// Todos_React/src/components/form/AddTodo.jsx
import React, { Component } from "react";
import PropTypes from "prop-types";

class AddTodo extends Component {
	state = {
		title: "",
	};

	handleTitleChange = (e) =>
		this.setState({ [e.target.name]: e.target.value });

	onSubmit = (e) => {
		e.preventDefault();
		this.props.handleAdd(this.state.title);
		this.setState({ title: "" });
	};

	render() {
		return (
			<div>
				<form onSubmit={this.onSubmit} style={{ display: "flex" }}>
					<input
						type="text"
						name="title"
						placeholder="Add Todo..."
						style={{ flex: "10", padding: "5px" }}
						value={this.state.title}
						onChange={this.handleTitleChange}
					/>
					<input
						type="submit"
						value="Submit"
						className="btn"
						style={{ flex: "1" }}
					/>
				</form>
			</div>
		);
	}
}

AddTodo.propTypes = {
	addTodo: PropTypes.func,
};

export default AddTodo;
