// Todos_Angular/src/app/components/add-todo/add-todo.component.ts
import { Component, OnInit, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-add-todo',
  templateUrl: './add-todo.component.html',
  styleUrls: ['./add-todo.component.css'],
})
export class AddTodoComponent implements OnInit {
  @Output() addTodo: EventEmitter<any> = new EventEmitter

  title: string;

  onSubmit() {
    const newTodo = {
      title: this.title,
      completed: false,
    };

    this.addTodo.emit(newTodo)
  }

  constructor() {}

  ngOnInit(): void {}
}

<form class="form" (ngSubmit)="onSubmit()">
  <input
    type="text"
    name="title"
    [(ngModel)]="title"
    placeholder="Add Todo..."
  /><input type="submit" value="Submit" class="btn" />
</form>

// Todos_Vue/src/components/form/AddTodo.vue
<template>
	<div>
		<form v-on:submit.prevent="onSubmit">
			<input
				type="text"
				v-model="title"
				name="title"
				placeholder="Add Todo..."
			/>
			<input type="submit" value="Submit" class="btn" />
		</form>
	</div>
</template>

<script>
export default {
	name: "AddTodo",
	data() {
		return {
			title: "",
		};
	},
	methods: {
		onSubmit() {
			const newTodo = {
				title: this.title,
				completed: false,
			};
			this.$emit("add-todo", newTodo);

			this.title = "";
		},
	},
};
</script>

<style scoped>
form {
	display: flex;
}

input[type="text"] {
	flex: 10;
	padding: 5px;
}

input[type="submit"] {
	flex: 1;
}
</style>
